# Importing Libraries

In [4]:
import pandas as pd
import numpy as np 

# Numpy - Split

In [3]:
x =np.arange(20).reshape(5,4)
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [7]:
np.split(x,[1,3])

[array([[0, 1, 2, 3]]),
 array([[ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]),
 array([[12, 13, 14, 15],
        [16, 17, 18, 19]])]

In [8]:
 part1,part2,part3   = np.split(x,[1,3])

In [9]:
part1

array([[0, 1, 2, 3]])

In [10]:
part2

array([[ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [11]:
part3

array([[12, 13, 14, 15],
       [16, 17, 18, 19]])

In [12]:
  splitted = np.split(x,[1,3])

In [13]:
splitted[0]

array([[0, 1, 2, 3]])

In [14]:
splitted[1]

array([[ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [16]:
splitted[2]

array([[12, 13, 14, 15],
       [16, 17, 18, 19]])

#  Using List 

In [5]:
data =[1,2,3,4,5]
data

[1, 2, 3, 4, 5]

In [6]:
seri = pd.Series(data)
seri

0    1
1    2
2    3
3    4
4    5
dtype: int64